import React, { useEffect, useMemo, useState } from "react";
import { Alert, Button, Card, Empty, Form, Modal, Skeleton, Table, Tabs, message } from "antd";
import { useDispatch, useSelector } from "react-redux";
import PayrollStatusTag from "../components/PayrollStatusTag";
import PayrollStatsCards from "../components/PayrollStatsCards";
import PayrollFilters from "../components/PayrollFilters";
import PayrollPermissionGuard, { getRoleName } from "../components/PayrollPermissionGuard";
import SalaryComponentForm from "../components/SalaryComponentForm";
import SalaryStructureBuilder from "../components/SalaryStructureBuilder";
import PayrollCycleForm from "../components/PayrollCycleForm";
import PayrollRunTable from "../components/PayrollRunTable";
import PayslipPreview from "../components/PayslipPreview";
import PayrollApprovalTimeline from "../components/PayrollApprovalTimeline";
import { fetchPayrollCycles, createPayrollCycle, lockPayrollCycle } from "../slices/payrollCycleSlice";
import { fetchSalaryComponents, createSalaryComponent, deleteSalaryComponent } from "../slices/salaryComponentSlice";
import { fetchSalaryStructures, createSalaryStructure, approveSalaryStructure } from "../slices/salaryStructureSlice";
import { fetchPayrollRunItems, calculatePayrollRun, approvePayrollRun, markPayrollPaid } from "../slices/payrollRunSlice";
import { fetchPayslips, generatePayslips, publishPayslips } from "../slices/payslipSlice";
import { fetchEmployeeLoans, createEmployeeLoan } from "../slices/employeeLoanSlice";
import { fetchPayrollSummaryReport, fetchPayrollAuditLogs } from "../slices/payrollReportSlice";
import { savePayrollSettings } from "../slices/payrollSettingSlice";
import { buildPayrollScope, payrollApi } from "../services/payrollApi";

const money = (v) => `₹${Number(v || 0).toLocaleString("en-IN")}`;
const useUser = () => useSelector((state) => state.auth.user);
const ActionButton = ({ user, permission, children, ...props }) => <PayrollPermissionGuard user={user} permission={permission}><Button {...props}>{children}</Button></PayrollPermissionGuard>;
const PageHeader = ({ title, subtitle, children }) => <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="m-0 text-2xl font-semibold text-slate-900">{title}</h1><p className="m-0 text-sm text-slate-500">{subtitle}</p></div><div className="flex flex-wrap gap-2">{children}</div></div>;
const SafeTable = ({ columns, dataSource, loading }) => loading ? <Skeleton active /> : <Table rowKey="_id" dataSource={dataSource} columns={columns} scroll={{ x: 1000 }} pagination={{ pageSize: 10 }} locale={{ emptyText: <Empty description="No payroll records found" /> }} />;

export const PayrollDashboard = () => { const dispatch=useDispatch(); const user=useUser(); const { items=[] }=useSelector(s=>s.payrollCycles||{}); const report=useSelector(s=>s.payrollReports?.summary); useEffect(()=>{dispatch(fetchPayrollCycles());dispatch(fetchPayrollSummaryReport());},[dispatch]); const latest=items[0]||{}; return <div className="p-4"><PageHeader title="Payroll Dashboard" subtitle="Current cycle, approvals, compliance dues and payroll trends"><ActionButton user={user} permission="payroll.cycles.manage" type="primary">Create Payroll Cycle</ActionButton></PageHeader><PayrollStatsCards totalEmployees={latest.totalEmployees} grossPay={latest.grossPay||report?.cards?.grossPay} netPay={latest.netPay||report?.cards?.netPay} deductions={latest.deductions||report?.cards?.deductions} employerContribution={latest.employerContribution||report?.cards?.employerContribution} pendingApprovals={items.filter(i=>i.status==="review").length} /><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-3"><Card title="Department-wise payroll cost"><Empty description="Chart appears after payroll calculation" /></Card><Card title="Earnings vs deductions"><Empty description="No chart data" /></Card><Card title="Payroll trend by month"><Empty description="No trend data" /></Card></div><Card title="Current Payroll Cycle" className="mt-4"><SafeTable dataSource={items} columns={["month","year","status","totalEmployees","grossPay","deductions","netPay","paymentDate"].map(k=>({title:k,dataIndex:k,render:k==="status"?(s)=><PayrollStatusTag status={s}/>:undefined})).concat({title:"Actions",render:(_,r)=><div className="flex gap-2"><ActionButton user={user} permission="payroll.runs.manage" onClick={()=>dispatch(calculatePayrollRun(r._id))}>Process Payroll</ActionButton><ActionButton user={user} permission="payroll.approve" onClick={()=>dispatch(approvePayrollRun(r._id))}>Approve</ActionButton></div>})} /></Card><Card title="Pending Payroll Actions" className="mt-4"><SafeTable dataSource={items.filter(i=>["review","draft"].includes(i.status))} columns={[{title:"Type",render:()=>"Payroll Cycle"},{title:"Employee",render:()=>"All employees"},{title:"Amount",dataIndex:"netPay",render:money},{title:"Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Requested By",dataIndex:"createdBy"},{title:"Created Date",dataIndex:"createdAt"},{title:"Actions",render:()=>"Review"}]} /></Card></div> };

export const PayrollSettingsPage = () => { const [form]=Form.useForm(); const dispatch=useDispatch(); return <div className="p-4"><PageHeader title="Payroll Settings" subtitle="Configure salary frequency, working days, statutory PF/ESI/TDS/PT and rounding" /><Card><Form form={form} layout="vertical" initialValues={{ payrollEnabled:true, salaryFrequency:"monthly", workingDaysMethod:"attendance_days", currency:"INR", roundingMethod:"nearest", pf:{enabled:false,wageCeiling:15000}, esi:{enabled:false,wageCeiling:21000}, tds:{enabled:false}, professionalTax:{enabled:false} }} onFinish={(v)=>dispatch(savePayrollSettings(v)).unwrap().then(()=>message.success("Settings saved")).catch(message.error)}><div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Form.Item label="Payroll Enabled" name="payrollEnabled" valuePropName="checked"><input type="checkbox" /></Form.Item><Form.Item label="Salary Frequency" name="salaryFrequency"><select><option value="monthly">Monthly</option></select></Form.Item><Form.Item label="Default Pay Day" name="defaultPayDay"><input type="number" className="ant-input" /></Form.Item><Form.Item label="Working Days Method" name="workingDaysMethod"><select><option value="attendance_days">Attendance Days</option><option value="calendar_days">Calendar Days</option><option value="fixed_days">Fixed Days</option></select></Form.Item><Form.Item label="Currency" name="currency"><input className="ant-input" /></Form.Item><Form.Item label="Rounding Method" name="roundingMethod"><select><option value="nearest">Nearest</option><option value="ceil">Ceil</option><option value="floor">Floor</option><option value="none">None</option></select></Form.Item><Form.Item label="PF Enabled" name={["pf","enabled"]} valuePropName="checked"><input type="checkbox" /></Form.Item><Form.Item label="PF Wage Ceiling" name={["pf","wageCeiling"]}><input type="number" className="ant-input" /></Form.Item><Form.Item label="ESI Enabled" name={["esi","enabled"]} valuePropName="checked"><input type="checkbox" /></Form.Item><Form.Item label="ESI Wage Ceiling" name={["esi","wageCeiling"]}><input type="number" className="ant-input" /></Form.Item><Form.Item label="TDS Enabled" name={["tds","enabled"]} valuePropName="checked"><input type="checkbox" /></Form.Item><Form.Item label="Professional Tax Enabled" name={["professionalTax","enabled"]} valuePropName="checked"><input type="checkbox" /></Form.Item></div><Button type="primary" htmlType="submit">Save Settings</Button><Button className="ml-2" onClick={()=>form.resetFields()}>Reset to Default</Button></Form></Card></div> };

export const SalaryComponentsPage = () => { const dispatch=useDispatch(); const user=useUser(); const [open,setOpen]=useState(false); const [form]=Form.useForm(); const state=useSelector(s=>s.salaryComponents||{}); useEffect(()=>{dispatch(fetchSalaryComponents())},[dispatch]); return <div className="p-4"><PageHeader title="Salary Components" subtitle="Manage earnings, deductions and employer contribution templates"><ActionButton user={user} permission="payroll.components.manage" type="primary" onClick={()=>setOpen(true)}>Add Component</ActionButton></PageHeader><SafeTable loading={state.loading} dataSource={state.items} columns={["name","code","type","calculationType","percentageOf","value","taxable","pfApplicable","esiApplicable"].map(k=>({title:k,dataIndex:k,render:(v)=>typeof v==="boolean"?(v?"Yes":"No"):v})).concat([{title:"Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Actions",render:(_,r)=><ActionButton user={user} permission="payroll.components.manage" danger onClick={()=>Modal.confirm({title:"Deactivate component?",onOk:()=>dispatch(deleteSalaryComponent(r._id))})}>Delete/Deactivate</ActionButton>}])} /><Modal open={open} title="Add Salary Component" onCancel={()=>setOpen(false)} onOk={()=>form.validateFields().then(v=>dispatch(createSalaryComponent(v)).unwrap()).then(()=>{message.success("Component saved");setOpen(false);dispatch(fetchSalaryComponents())}).catch(message.error)}><SalaryComponentForm form={form} /></Modal></div> };

export const SalaryStructurePage = () => { const dispatch=useDispatch(); const user=useUser(); const [open,setOpen]=useState(false); const [form]=Form.useForm(); const state=useSelector(s=>s.salaryStructures||{}); useEffect(()=>{dispatch(fetchSalaryStructures())},[dispatch]); return <div className="p-4"><PageHeader title="Salary Structures" subtitle="Create, revise and approve employee CTC structures"><ActionButton user={user} permission="payroll.salaryStructure.manage" type="primary" onClick={()=>setOpen(true)}>Create Salary Structure</ActionButton></PageHeader><PayrollFilters /><SafeTable loading={state.loading} dataSource={state.items} columns={[{title:"Employee Name",dataIndex:["employeeId","employeeCode"]},{title:"Employee Code",dataIndex:["employeeId","employeeCode"]},{title:"Department",dataIndex:["employeeId","department"]},{title:"Designation",dataIndex:["employeeId","designation"]},{title:"Effective From",dataIndex:"effectiveFrom"},{title:"Gross Monthly",dataIndex:"grossMonthly",render:money},{title:"Net Monthly Estimate",dataIndex:"netMonthly",render:money},{title:"CTC Monthly",dataIndex:"ctcMonthly",render:money},{title:"Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Approved By",dataIndex:"approvedBy"},{title:"Actions",render:(_,r)=><div className="flex gap-2"><Button>View</Button><ActionButton user={user} permission="payroll.approve" onClick={()=>dispatch(approveSalaryStructure(r._id))}>Approve</ActionButton></div>}]} /><Modal width={1100} open={open} title="Salary Structure Builder" onCancel={()=>setOpen(false)} onOk={()=>form.submit()}><SalaryStructureBuilder form={form} onFinish={(v)=>dispatch(createSalaryStructure(v)).unwrap().then(()=>{message.success("Structure saved");setOpen(false);dispatch(fetchSalaryStructures())}).catch(message.error)} /></Modal></div> };

export const EmployeeSalaryProfile = () => <SalaryStructurePage />;
export const PayrollCyclePage = () => { const dispatch=useDispatch(); const user=useUser(); const [open,setOpen]=useState(false); const [form]=Form.useForm(); const state=useSelector(s=>s.payrollCycles||{}); useEffect(()=>{dispatch(fetchPayrollCycles())},[dispatch]); const act=(text,permission,fn)=><ActionButton user={user} permission={permission} onClick={fn}>{text}</ActionButton>; return <div className="p-4"><PageHeader title="Payroll Cycles" subtitle="Create monthly cycles, process payroll, pay and lock"><ActionButton user={user} permission="payroll.cycles.manage" type="primary" onClick={()=>setOpen(true)}>Create Cycle</ActionButton></PageHeader><SafeTable loading={state.loading} dataSource={state.items} columns={["cycleName","month","year","startDate","endDate","paymentDate","totalEmployees","grossPay","deductions","netPay"].map(k=>({title:k,dataIndex:k,render:["grossPay","deductions","netPay"].includes(k)?money:undefined})).concat([{title:"Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Actions",render:(_,r)=><div className="flex flex-wrap gap-2">{act("Calculate","payroll.runs.manage",()=>dispatch(calculatePayrollRun(r._id)))}{act("Approve","payroll.approve",()=>dispatch(approvePayrollRun(r._id)))}{act("Generate Payslips","payroll.payslips.manage",()=>dispatch(generatePayslips(r._id)))}{act("Publish","payroll.payslips.manage",()=>dispatch(publishPayslips(r._id)))}{act("Mark Paid","payroll.runs.manage",()=>dispatch(markPayrollPaid(r._id)))}{act("Lock","payroll.cycles.manage",()=>Modal.confirm({title:"Lock payroll cycle?",onOk:()=>dispatch(lockPayrollCycle(r._id))}))}</div>}])} /><Modal open={open} title="Create Payroll Cycle" onCancel={()=>setOpen(false)} onOk={()=>form.validateFields().then(v=>dispatch(createPayrollCycle(v)).unwrap()).then(()=>{message.success("Cycle created");setOpen(false);dispatch(fetchPayrollCycles())}).catch(message.error)}><PayrollCycleForm form={form} /></Modal></div> };
export const PayrollRunPage = () => { const dispatch=useDispatch(); const state=useSelector(s=>s.payrollRuns||{}); const cycleId=window.location.pathname.split("/").pop(); useEffect(()=>{ if(cycleId&&!cycleId.includes("runs")) dispatch(fetchPayrollRunItems(cycleId)); },[dispatch,cycleId]); return <div className="p-4"><PageHeader title="Payroll Run" subtitle="Review employee-wise earnings, deductions, statutory and net salary"><PayrollApprovalTimeline status="review" /></PageHeader><PayrollRunTable items={state.items} loading={state.loading} /></div> };
export const PayslipPage = () => { const dispatch=useDispatch(); const state=useSelector(s=>s.payslips||{}); const [active,setActive]=useState(null); useEffect(()=>{dispatch(fetchPayslips())},[dispatch]); return <div className="p-4"><PageHeader title="Payslips" subtitle="Generate, preview, publish, email and download payslips" /><PayrollFilters /><SafeTable dataSource={state.items} columns={["payslipNumber","month","year","grossPay","deductions","netPay","generatedAt"].map(k=>({title:k,dataIndex:k,render:["grossPay","deductions","netPay"].includes(k)?money:undefined})).concat([{title:"Published Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Actions",render:(_,r)=><div className="flex gap-2"><Button onClick={()=>setActive(r)}>Preview</Button><Button>Download PDF</Button><Button>Send Email</Button></div>}])} /><Modal width={900} open={!!active} onCancel={()=>setActive(null)} footer={null}><PayslipPreview payslip={active}/></Modal></div> };
export const MyPayslipsPage = () => { const [items,setItems]=useState([]); const [loading,setLoading]=useState(false); const [active,setActive]=useState(null); const scope=useSelector(buildPayrollScope); useEffect(()=>{ setLoading(true); payrollApi.payslips.mine(scope).then(setItems).catch((e)=>message.error(e?.response?.data?.message||"My payslips load failed")).finally(()=>setLoading(false)); },[scope?.schoolId,scope?.academicYearId]); return <div className="p-4"><PageHeader title="My Payslips" subtitle="View published payslips and download salary slips" /><SafeTable loading={loading} dataSource={items} columns={[{title:"Month",render:(_,r)=>`${r.month}/${r.year}`},{title:"Gross",dataIndex:"grossPay",render:money},{title:"Deductions",dataIndex:"deductions",render:money},{title:"Net Pay",dataIndex:"netPay",render:money},{title:"Payment",dataIndex:"paymentStatus",render:s=><PayrollStatusTag status={s}/>},{title:"Actions",render:(_,r)=><Button onClick={()=>setActive(r)}>Preview / Download</Button>}]} /><Modal open={!!active} onCancel={()=>setActive(null)} footer={null} width={720}><PayslipPreview payslip={active}/></Modal></div> };

export const EmployeeLoanPage = () => { const dispatch=useDispatch(); const state=useSelector(s=>s.employeeLoans||{}); useEffect(()=>{dispatch(fetchEmployeeLoans())},[dispatch]); return <div className="p-4"><PageHeader title="Employee Loans & Advances" subtitle="Request, approve, reject and close salary advances" /><Card title="Loan Request Form" className="mb-4"><Alert type="info" showIcon message="Fields: Employee, Loan Type, Principal Amount, EMI Amount, Installments, Start Month, Reason, Attachment" /><Button type="primary" className="mt-3" onClick={()=>dispatch(createEmployeeLoan({loanType:"advance",principalAmount:0,status:"pending"}))}>Submit Request</Button></Card><SafeTable dataSource={state.items} columns={["employeeId","loanType","principalAmount","emiAmount","totalInstallments","paidInstallments","balance","startMonth"].map(k=>({title:k,dataIndex:k})).concat([{title:"Status",dataIndex:"status",render:s=><PayrollStatusTag status={s}/>},{title:"Actions",render:()=>"Approve / Reject / Close"}])} /></div> };
export const TaxDeclarationPage = () => <div className="p-4"><PageHeader title="Tax Declarations" subtitle="PAN, tax regime, investment declarations, HRA and proof uploads" /><Card><Alert type="info" showIcon message="Actions: Save Draft, Submit Declaration, Upload Proof, View Status" /></Card></div>;
export const PayrollReportsPage = () => { const dispatch=useDispatch(); const report=useSelector(s=>s.payrollReports?.summary); useEffect(()=>{dispatch(fetchPayrollSummaryReport())},[dispatch]); const rows=["Payroll Summary","Department Cost Report","Employee Salary Register","Bank Transfer Report","PF Report","ESI Report","TDS Report","Professional Tax Report","Loan Deduction Report"].map((name,i)=>({_id:i,name,type:name.split(" ")[0],month:"Current",year:new Date().getFullYear()})); return <div className="p-4"><PageHeader title="Payroll Reports" subtitle="Summary, department cost, bank exports and statutory reports" /><PayrollStatsCards grossPay={report?.cards?.grossPay} netPay={report?.cards?.netPay} deductions={report?.cards?.deductions} employerContribution={report?.cards?.employerContribution} /><Card className="mt-4"><SafeTable dataSource={rows} columns={[{title:"Report Name",dataIndex:"name"},{title:"Type",dataIndex:"type"},{title:"Month",dataIndex:"month"},{title:"Year",dataIndex:"year"},{title:"Generated By",render:()=>"System"},{title:"Generated At",render:()=>new Date().toLocaleString()},{title:"Actions",render:()=>"View / Export Excel / Export PDF / Download Bank File"}]} /></Card></div> };
export const SuperAdminPayrollOverview = () => <div className="p-4"><PageHeader title="Payroll Management Overview" subtitle="View payroll module usage across all schools" /><PayrollStatsCards totalEmployees={0} grossPay={0} netPay={0} deductions={0} employerContribution={0} pendingApprovals={0} /><Card className="mt-4" title="School Payroll Usage"><SafeTable dataSource={[]} columns={["School Name","Plan","Payroll Enabled","Employees Count","Last Payroll Month","Last Payroll Status","Monthly Payroll Cost","Subscription Status","Actions"].map(t=>({title:t,dataIndex:t}))} /></Card></div>;
export const PrincipalPayrollApprovalPage = () => <div className="p-4"><PageHeader title="Principal Payroll Approvals" subtitle="Review, approve, reject or send payroll back for correction" /><PayrollDashboard /></div>;
export const AccountantPayrollWorkspace = () => <div className="p-4"><PageHeader title="Accountant Payroll Workspace" subtitle="Cycles, runs, adjustments, payslips and bank exports" /><Tabs items={[{key:"cycles",label:"Payroll Cycles",children:<PayrollCyclePage/>},{key:"run",label:"Payroll Run",children:<PayrollRunPage/>},{key:"adjustments",label:"Adjustments",children:<Card>Fields: Employee, Type, Amount, Month, Reason, Attachment, Taxable, Status</Card>},{key:"payslips",label:"Payslips",children:<PayslipPage/>},{key:"bank",label:"Bank Export",children:<PayrollReportsPage/>}]} /></div>;
export const HRSalaryManagementPage = () => <div className="p-4"><PageHeader title="HR Salary Management" subtitle="Salary structures, employee loans, tax declarations and revisions" /><Tabs items={[{key:"salary",label:"Salary Structures",children:<SalaryStructurePage/>},{key:"loans",label:"Employee Loans",children:<EmployeeLoanPage/>},{key:"tax",label:"Tax Declarations",children:<TaxDeclarationPage/>},{key:"revision",label:"Salary Revision",children:<SalaryStructurePage/>}]} /></div>;
export const EmployeeLoanManagementPage = () => <EmployeeLoanPage />;
export const MyPayrollDashboard = () => <div className="p-4"><PageHeader title="My Payroll Dashboard" subtitle="Salary structure, payslips, loan requests and tax declaration" /><PayrollStatsCards grossPay={0} netPay={0} deductions={0} /><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Card title="My Salary Structure"><Button>View Salary Structure</Button></Card><Card title="My Payslips"><Button>View Payslip</Button><Button className="ml-2">Download Payslip</Button></Card><Card title="My Loan / Advance Requests"><Button>Request Loan/Advance</Button></Card><Card title="My Tax Declaration"><Button>Submit Tax Declaration</Button></Card></div></div>;
export const MyLoanRequestPage = () => <EmployeeLoanPage />;
export const MyTaxDeclarationPage = () => <TaxDeclarationPage />;
export const PayrollAuditReportsPage = () => { const dispatch=useDispatch(); const logs=useSelector(s=>s.payrollReports?.auditLogs||[]); useEffect(()=>{dispatch(fetchPayrollAuditLogs())},[dispatch]); return <div className="p-4"><PageHeader title="Payroll Audit Reports" subtitle="Read-only payroll summary and audit logs" /><PayrollStatsCards grossPay={0} netPay={0} deductions={0} pendingApprovals={0}/><Card title="Audit Logs" className="mt-4"><SafeTable dataSource={logs} columns={["action","entity","employeeId","performedBy","role","createdAt","ipAddress","remarks"].map(k=>({title:k,dataIndex:k}))} /></Card></div> };
