import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Alert, App, Button, Card, Col, DatePicker, Empty, Form, Input, InputNumber, List, Modal, Popconfirm, Row, Select, Skeleton, Space, Statistic, Switch, Table, Tabs, Tag, Tooltip, Typography } from "antd";
import { BankOutlined, CheckCircleOutlined, CloudDownloadOutlined, DollarOutlined, FileDoneOutlined, LockOutlined, PlusOutlined, ReloadOutlined, SettingOutlined, UserOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import { useParams } from "react-router-dom";
import { fetchPayrollSettings, createPayrollSettings, updatePayrollSettings } from "../../features/payrollSettingsSlice";
import { fetchSalaryComponent, createSalaryComponent, updateSalaryComponent, deleteSalaryComponent } from "../../features/salaryComponentSlice";
import { fetchPayrollEmployee } from "../../features/payrollEmployeeSlice";
import { fetchPayrollStructure, createPayrollStructure, updatePayrollStructure } from "../../features/payrollStructureSlice";
import { fetchPayrollCycle, createPayrollCycle, updatePayrollCycle } from "../../features/payrollCycleSlice";
import { fetchPayslip } from "../../features/payslipSlice";
import { fetchPayrollReport } from "../../features/payrollReportSlice";
import { fetchEmployeeLoan, createEmployeeLoan } from "../../features/employeeLoanSlice";
import { fetchReimbursement, createReimbursement, updateReimbursement } from "../../features/reimbursementSlice";
import httpClient from "../../api/httpClient";
import { getErrorMessage } from "./../../utils/errorMessage";

const { Title, Text } = Typography;
const INR = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const monthOptions = dayjs.monthsShort?.() || ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const currency = (value) => INR.format(Number(value || 0));
const safeArray = (value) => Array.isArray(value) ? value : [];
const statusColor = (status) => ({ draft: "default", processing: "processing", pending_approval: "warning", approved: "success", paid: "blue", locked: "purple", active: "success", hold: "warning", inactive: "default", pending: "warning", rejected: "error" }[status] || "default");
const titleize = (value = "") => String(value || "-").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const useResource = (key) => useSelector((state) => state[key] || { items: [], loading: false, error: null, selected: null });

function PageShell({ title, subtitle, actions, children, error }) {
  return <div style={{ padding: 24, maxWidth: 1440, margin: "0 auto" }}>
    <Space direction="vertical" size="large" style={{ width: "100%" }}>
      <Row justify="space-between" align="middle" gutter={[16, 16]}>
        <Col><Title level={3} style={{ margin: 0 }}>{title}</Title><Text type="secondary">{subtitle}</Text></Col>
        <Col><Space wrap>{actions}</Space></Col>
      </Row>
      {error ? <Alert type="error" showIcon message={getErrorMessage(error)} /> : null}
      {children}
    </Space>
  </div>;
}

function ResponsiveTable({ columns, dataSource, loading, rowKey = "_id", empty = "No payroll records found", mobileTitle }) {
  return <>
    <div className="hidden md:block"><Table rowKey={rowKey} columns={columns} dataSource={safeArray(dataSource)} loading={loading} scroll={{ x: 900 }} pagination={{ pageSize: 10 }} locale={{ emptyText: <Empty description={empty} /> }} /></div>
    <div className="md:hidden"><Skeleton loading={loading} active><List dataSource={safeArray(dataSource)} locale={{ emptyText: <Empty description={empty} /> }} renderItem={(item) => <List.Item><Card size="small" style={{ width: "100%" }}><Space direction="vertical" style={{ width: "100%" }}><Text strong>{mobileTitle ? mobileTitle(item) : item.name || item.title || item.employeeId?.name || "Payroll record"}</Text>{columns.slice(0, 5).map((column) => <Row key={column.key || column.dataIndex} justify="space-between"><Text type="secondary">{column.title}</Text><span>{column.render ? column.render(item[column.dataIndex], item) : String(item[column.dataIndex] ?? "-")}</span></Row>)}</Space></Card></List.Item>} /></Skeleton></div>
  </>;
}

function StatCards({ summary = {}, loading }) {
  const cards = [
    ["Current Payroll", summary.currentPayroll || summary.netSalary || 0, <DollarOutlined />],
    ["Employees", summary.totalEmployees || summary.employees || 0, <UserOutlined />],
    ["Gross Salary", summary.grossAmount || summary.grossSalary || 0, <BankOutlined />],
    ["Deductions", summary.deductionAmount || summary.totalDeductions || 0, <FileDoneOutlined />],
    ["Net Payable", summary.netPayable || summary.netSalary || 0, <CheckCircleOutlined />],
    ["Pending Approvals", summary.pendingApprovals || 0, <ReloadOutlined />],
  ];
  return <Row gutter={[16, 16]}>{cards.map(([label, value, icon]) => <Col xs={24} sm={12} lg={8} xl={4} key={label}><Card loading={loading}><Statistic title={label} value={label === "Employees" || label === "Pending Approvals" ? value : currency(value)} prefix={icon} /></Card></Col>)}</Row>;
}

export function PayrollDashboard() {
  const dispatch = useDispatch();
  const cycles = useResource("payrollCycle");
  const reports = useResource("payrollReport");
  useEffect(() => { dispatch(fetchPayrollCycle()); dispatch(fetchPayrollReport()); }, [dispatch]);
  const latest = safeArray(cycles.items)[0] || {};
  const summary = { ...(reports.selected || reports.items?.[0]), ...latest, pendingApprovals: safeArray(cycles.items).filter((cycle) => cycle.status === "pending_approval").length };
  return <PageShell title="Payroll Dashboard" subtitle="Enterprise payroll control center with school-scoped salary processing." error={cycles.error || reports.error} actions={<Button icon={<ReloadOutlined />} onClick={() => dispatch(fetchPayrollCycle())}>Refresh</Button>}>
    <StatCards summary={summary} loading={cycles.loading || reports.loading} />
    <Row gutter={[16, 16]}><Col xs={24} lg={14}><Card title="Payroll Cost Trend"><div style={{ height: 220, display: "grid", alignItems: "end", gridTemplateColumns: "repeat(6, 1fr)", gap: 12 }}>{safeArray(cycles.items).slice(0, 6).reverse().map((cycle) => <Tooltip title={`${cycle.name}: ${currency(cycle.netPayable)}`} key={cycle._id}><div style={{ background: "linear-gradient(180deg,#1677ff,#69b1ff)", height: Math.max(20, Math.min(200, Number(cycle.netPayable || 0) / 1000)), borderRadius: 8 }} /></Tooltip>)}</div></Card></Col><Col xs={24} lg={10}><Card title="Department-wise Salary"><Empty description="Department analytics will populate after employee departments are mapped." /></Card></Col></Row>
    <Card title="Recent Payroll Cycles"><CycleTable data={cycles.items} loading={cycles.loading} compact /></Card>
  </PageShell>;
}

export function PayrollSettingsPage() {
  const dispatch = useDispatch();
  const { message } = App.useApp();
  const settings = useResource("payrollSettings");
  const [form] = Form.useForm();
  useEffect(() => { dispatch(fetchPayrollSettings()).unwrap().then((res) => form.setFieldsValue(res?.data || {})).catch(() => {}); }, [dispatch, form]);
  const save = async (values) => {
    const action = settings.selected?._id ? updatePayrollSettings({ id: settings.selected._id, data: values }) : createPayrollSettings(values);
    await dispatch(action).unwrap(); message.success("Payroll settings saved"); dispatch(fetchPayrollSettings());
  };
  return <PageShell title="Payroll Settings" subtitle="Configure statutory controls, currency and salary calculation policy." error={settings.error}>
    <Card loading={settings.loading}><Form form={form} layout="vertical" onFinish={save} initialValues={{ currency: "INR", salaryCalculationType: "fixed_monthly", payrollApprovalRequired: true }}><Row gutter={16}>{["pfEnabled", "esiEnabled", "tdsEnabled", "professionalTaxEnabled", "payrollApprovalRequired"].map((name) => <Col xs={24} md={8} key={name}><Form.Item name={name} label={titleize(name)} valuePropName="checked"><Switch /></Form.Item></Col>)}<Col xs={24} md={8}><Form.Item name="currency" label="Currency"><Input /></Form.Item></Col><Col xs={24} md={8}><Form.Item name="salaryCalculationType" label="Salary Calculation Type"><Select options={[{ value: "fixed_monthly", label: "Fixed Monthly" }, { value: "attendance_based", label: "Attendance Based" }]} /></Form.Item></Col></Row><Button type="primary" htmlType="submit" icon={<SettingOutlined />} loading={settings.loading}>Save Settings</Button></Form></Card>
  </PageShell>;
}

export function SalaryComponentsPage() {
  const dispatch = useDispatch();
  const { message } = App.useApp();
  const resource = useResource("salaryComponent");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form] = Form.useForm(); const [search, setSearch] = useState("");
  useEffect(() => { dispatch(fetchSalaryComponent({ search })); }, [dispatch, search]);
  const submit = async (values) => { await dispatch(editing ? updateSalaryComponent({ id: editing._id, data: values }) : createSalaryComponent(values)).unwrap(); message.success("Component saved"); setOpen(false); form.resetFields(); setEditing(null); dispatch(fetchSalaryComponent()); };
  const columns = [
    { title: "Name", dataIndex: "name" }, { title: "Code", dataIndex: "code" }, { title: "Type", dataIndex: "type", render: (v) => <Tag color={v === "earning" ? "green" : v === "deduction" ? "red" : "blue"}>{titleize(v)}</Tag> },
    { title: "Calculation", dataIndex: "calculationType", render: titleize }, { title: "Value", dataIndex: "value" }, { title: "Active", dataIndex: "isActive", render: (v) => <Tag color={v ? "success" : "default"}>{v ? "Active" : "Inactive"}</Tag> },
    { title: "Action", render: (_, row) => <Space><Button size="small" onClick={() => { setEditing(row); form.setFieldsValue(row); setOpen(true); }}>Edit</Button><Popconfirm title="Delete component?" onConfirm={async () => { await dispatch(deleteSalaryComponent(row._id)).unwrap(); message.success("Deleted"); }}><Button danger size="small">Delete</Button></Popconfirm></Space> },
  ];
  return <PageShell title="Salary Components" subtitle="Manage earnings, deductions and employer contribution definitions." error={resource.error} actions={<><Input.Search allowClear placeholder="Search components" onSearch={setSearch} /><Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>Add Component</Button></>}>
    <ResponsiveTable columns={columns} dataSource={resource.items} loading={resource.loading} />
    <Modal open={open} title={editing ? "Edit Component" : "Add Component"} onCancel={() => { setOpen(false); setEditing(null); form.resetFields(); }} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={submit} initialValues={{ type: "earning", calculationType: "fixed", value: 0, taxable: true, isActive: true }}><Form.Item name="name" label="Name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="code" label="Code" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="Type"><Select options={["earning", "deduction", "employer_contribution"].map((value) => ({ value, label: titleize(value) }))} /></Form.Item><Form.Item name="calculationType" label="Calculation Type"><Select options={["fixed", "percentage", "formula"].map((value) => ({ value, label: titleize(value) }))} /></Form.Item><Form.Item name="value" label="Value"><InputNumber min={0} style={{ width: "100%" }} /></Form.Item><Form.Item name="formula" label="Formula"><Input /></Form.Item><Space><Form.Item name="taxable" valuePropName="checked"><Switch checkedChildren="Taxable" unCheckedChildren="Non Tax" /></Form.Item><Form.Item name="statutory" valuePropName="checked"><Switch checkedChildren="Statutory" /></Form.Item><Form.Item name="isActive" valuePropName="checked"><Switch checkedChildren="Active" /></Form.Item></Space></Form></Modal>
  </PageShell>;
}

export function EmployeePayrollPage() {
  const dispatch = useDispatch(); const employees = useResource("payrollEmployee"); const [form] = Form.useForm(); const [selected, setSelected] = useState(null);
  useEffect(() => { dispatch(fetchPayrollEmployee()); }, [dispatch]);
  const columns = [{ title: "Employee", render: (_, r) => <Space direction="vertical" size={0}><Text strong>{r.name}</Text><Text type="secondary">{r.email}</Text></Space> }, { title: "Role", render: (_, r) => r.roleId?.name || "-" }, { title: "Salary Status", dataIndex: "salaryStatus", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }, { title: "Bank", dataIndex: "bankProfileComplete", render: (v) => <Tag color={v ? "success" : "warning"}>{v ? "Complete" : "Pending"}</Tag> }, { title: "Structure", dataIndex: "salaryStructureActive", render: (v) => <Tag color={v ? "success" : "default"}>{v ? "Active" : "Not Set"}</Tag> }, { title: "Action", render: (_, r) => <Button onClick={() => { setSelected(r); form.setFieldsValue(r.payrollProfile || {}); }}>View / Setup</Button> }];
  return <PageShell title="Employee Payroll" subtitle="School-scoped employee salary profiles, bank status and active structures." error={employees.error} actions={<Button icon={<ReloadOutlined />} onClick={() => dispatch(fetchPayrollEmployee())}>Refresh</Button>}><ResponsiveTable columns={columns} dataSource={employees.items} loading={employees.loading} mobileTitle={(r) => r.name} /><Modal open={Boolean(selected)} title={`Payroll Profile - ${selected?.name || "Employee"}`} onCancel={() => setSelected(null)} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={async (values) => { await httpClient.post(`/payroll/employees/${selected._id}/profile`, values); setSelected(null); dispatch(fetchPayrollEmployee()); }}><Form.Item name="designation" label="Designation"><Input /></Form.Item><Form.Item name="joiningDate" label="Joining Date"><DatePicker style={{ width: "100%" }} /></Form.Item><Form.Item name="salaryStatus" label="Salary Status"><Select options={["active", "hold", "inactive"].map((value) => ({ value, label: titleize(value) }))} /></Form.Item><Title level={5}>Bank Details</Title><Form.Item name={["bankDetails", "accountHolderName"]} label="Account Holder"><Input /></Form.Item><Form.Item name={["bankDetails", "bankName"]} label="Bank Name"><Input /></Form.Item><Form.Item name={["bankDetails", "accountNumber"]} label="Account Number"><Input /></Form.Item><Form.Item name={["bankDetails", "ifsc"]} label="IFSC"><Input /></Form.Item></Form></Modal></PageShell>;
}

export function SalaryStructurePage() {
  const dispatch = useDispatch(); const { message } = App.useApp(); const structures = useResource("payrollStructure"); const employees = useResource("payrollEmployee"); const [form] = Form.useForm(); const [open, setOpen] = useState(false);
  useEffect(() => { dispatch(fetchPayrollStructure()); dispatch(fetchPayrollEmployee()); }, [dispatch]);
  const columns = [{ title: "Employee", render: (_, r) => r.employeeId?.name || r.employeeId }, { title: "Effective", dataIndex: "effectiveFrom", render: (v) => v ? dayjs(v).format("DD MMM YYYY") : "-" }, { title: "Gross", dataIndex: "grossMonthly", render: currency }, { title: "Net", dataIndex: "netMonthly", render: currency }, { title: "Status", dataIndex: "status", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }, { title: "Action", render: (_, r) => <Popconfirm title="Activate this structure?" onConfirm={async () => { await dispatch(updatePayrollStructure({ id: r._id, actionPath: "/activate" })).unwrap(); message.success("Activated"); dispatch(fetchPayrollStructure()); }}><Button size="small">Activate</Button></Popconfirm> }];
  return <PageShell title="Salary Structures" subtitle="Create dynamic earning/deduction structures with gross, net and CTC preview." error={structures.error} actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>Create Structure</Button>}><ResponsiveTable columns={columns} dataSource={structures.items} loading={structures.loading} /><Modal width={860} open={open} title="Create Salary Structure" onCancel={() => setOpen(false)} onOk={() => form.submit()}><StructureForm form={form} employees={employees.items} onFinish={async (values) => { const payload = { ...values, effectiveFrom: values.effectiveFrom?.toISOString() }; await dispatch(createPayrollStructure(payload)).unwrap(); message.success("Structure created"); setOpen(false); form.resetFields(); dispatch(fetchPayrollStructure()); }} /></Modal></PageShell>;
}

function StructureForm({ form, employees, onFinish }) {
  const values = Form.useWatch([], form) || {}; const gross = sumAmounts(values.earnings); const deductions = sumAmounts(values.deductions); const net = gross - deductions;
  return <Form form={form} layout="vertical" onFinish={onFinish} initialValues={{ earnings: [{ name: "Basic", amount: 0 }], deductions: [], status: "draft" }}><Row gutter={16}><Col xs={24} md={12}><Form.Item name="employeeId" label="Employee" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={safeArray(employees).map((e) => ({ value: e._id, label: e.name }))} /></Form.Item></Col><Col xs={24} md={12}><Form.Item name="effectiveFrom" label="Effective From" rules={[{ required: true }]}><DatePicker style={{ width: "100%" }} /></Form.Item></Col></Row><Row gutter={16}><Col xs={24} lg={12}><ComponentRows name="earnings" label="Earnings" /></Col><Col xs={24} lg={12}><ComponentRows name="deductions" label="Deductions" /></Col></Row><Card><Row gutter={16}><Col span={8}><Statistic title="Gross" value={currency(gross)} /></Col><Col span={8}><Statistic title="Deductions" value={currency(deductions)} /></Col><Col span={8}><Statistic title="Net" value={currency(net)} /></Col></Row></Card></Form>;
}
const sumAmounts = (rows = []) => safeArray(rows).reduce((total, row) => total + Number(row?.amount || 0), 0);
function ComponentRows({ name, label }) { return <Card size="small" title={label}><Form.List name={name}>{(fields, { add, remove }) => <Space direction="vertical" style={{ width: "100%" }}>{fields.map((field) => <Row gutter={8} key={field.key}><Col span={14}><Form.Item {...field} name={[field.name, "name"]} rules={[{ required: true }]}><Input placeholder="Component" /></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name, "amount"]}><InputNumber min={0} style={{ width: "100%" }} /></Form.Item></Col><Col span={2}><Button danger onClick={() => remove(field.name)}>×</Button></Col></Row>)}<Button block onClick={() => add({ name: "", amount: 0 })}>Add {label}</Button></Space>}</Form.List></Card>; }

function CycleTable({ data, loading, compact = false }) { const dispatch = useDispatch(); const { message } = App.useApp(); const action = async (row, path, label) => { await dispatch(updatePayrollCycle({ id: row._id, actionPath: path })).unwrap(); message.success(label); dispatch(fetchPayrollCycle()); }; const columns = [{ title: "Cycle", dataIndex: "name" }, { title: "Period", render: (_, r) => `${monthOptions[(r.month || 1) - 1]} ${r.year}` }, { title: "Employees", dataIndex: "totalEmployees" }, { title: "Gross", dataIndex: "grossAmount", render: currency }, { title: "Deductions", dataIndex: "deductionAmount", render: currency }, { title: "Net", dataIndex: "netPayable", render: currency }, { title: "Status", dataIndex: "status", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }]; if (!compact) columns.push({ title: "Actions", render: (_, r) => <Space wrap><Button size="small" onClick={() => window.location.assign(`${window.location.pathname.replace(/\/payroll\/cycles.*/, "")}/payroll/cycles/${r._id}`)}>View</Button><Popconfirm title="Process payroll cycle?" onConfirm={() => action(r, "/process", "Processing started")}><Button size="small">Process</Button></Popconfirm><Popconfirm title="Approve cycle?" onConfirm={() => action(r, "/approve", "Approved")}><Button size="small">Approve</Button></Popconfirm><Button size="small" onClick={() => action(r, "/mark-paid", "Marked paid")}>Paid</Button><Popconfirm title="Lock cycle permanently?" onConfirm={() => action(r, "/lock", "Locked")}><Button size="small" icon={<LockOutlined />}>Lock</Button></Popconfirm></Space> }); return <ResponsiveTable columns={columns} dataSource={data} loading={loading} />; }

export function PayrollCyclesPage() { const dispatch = useDispatch(); const { message } = App.useApp(); const cycles = useResource("payrollCycle"); const [open, setOpen] = useState(false); const [form] = Form.useForm(); useEffect(() => { dispatch(fetchPayrollCycle()); }, [dispatch]); return <PageShell title="Payroll Cycles" subtitle="Create, process, approve, mark paid and lock monthly payroll cycles." error={cycles.error} actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>Create Cycle</Button>}><CycleTable data={cycles.items} loading={cycles.loading} /><Modal open={open} title="Create Payroll Cycle" onCancel={() => setOpen(false)} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={async (values) => { await dispatch(createPayrollCycle(values)).unwrap(); message.success("Payroll cycle created"); setOpen(false); form.resetFields(); dispatch(fetchPayrollCycle()); }}><Form.Item name="name" label="Name"><Input /></Form.Item><Row gutter={16}><Col span={12}><Form.Item name="month" label="Month" rules={[{ required: true }]}><Select options={monthOptions.map((m, i) => ({ value: i + 1, label: m }))} /></Form.Item></Col><Col span={12}><Form.Item name="year" label="Year" rules={[{ required: true }]}><InputNumber min={2020} max={2100} style={{ width: "100%" }} /></Form.Item></Col></Row><Form.Item name="payDate" label="Pay Date"><DatePicker style={{ width: "100%" }} /></Form.Item></Form></Modal></PageShell>; }

export function PayrollCycleDetailPage() { const [detail, setDetail] = useState(null); const [loading, setLoading] = useState(true); const { id } = useParams(); useEffect(() => { httpClient.get(`/payroll/cycles/${id}`).then((res) => setDetail(res.data.data)).finally(() => setLoading(false)); }, [id]); const cycle = detail?.cycle || {}; const columns = [{ title: "Employee", render: (_, r) => r.employeeId?.name || r.employeeId }, { title: "Gross", dataIndex: "grossSalary", render: currency }, { title: "Deductions", dataIndex: "totalDeductions", render: currency }, { title: "Net", dataIndex: "netSalary", render: currency }, { title: "Status", dataIndex: "paymentStatus", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }, { title: "Payslip", render: (_, r) => <Button icon={<CloudDownloadOutlined />} href={`/api/v1/payroll/payslips/${r._id}/download`}>Download</Button> }]; return <PageShell title="Payroll Cycle Detail" subtitle="Review employee payroll run items, generate payslips and export compliance reports." actions={<Space wrap><Button onClick={() => httpClient.post(`/payroll/cycles/${id}/generate-payslips`)}>Generate Payslips</Button><Button href={`/api/v1/payroll/reports/bank-export?cycleId=${id}&format=csv`}>Bank Export</Button><Button href={`/api/v1/payroll/reports/pf?cycleId=${id}&format=csv`}>PF</Button><Button href={`/api/v1/payroll/reports/esi?cycleId=${id}&format=csv`}>ESI</Button><Button href={`/api/v1/payroll/reports/tds?cycleId=${id}&format=csv`}>TDS</Button></Space>}><StatCards summary={cycle} loading={loading} /><Card title="Run Items"><ResponsiveTable columns={columns} dataSource={detail?.items} loading={loading} /></Card></PageShell>; }

export function PayrollApprovalsPage() { const dispatch = useDispatch(); const cycles = useResource("payrollCycle"); useEffect(() => { dispatch(fetchPayrollCycle({ status: "pending_approval" })); }, [dispatch]); return <PageShell title="Payroll Approvals" subtitle="Pending payroll approvals and approval history."><CycleTable data={cycles.items} loading={cycles.loading} /></PageShell>; }
export function PayslipAdminPage() { const dispatch = useDispatch(); const payslip = useResource("payslip"); useEffect(() => { dispatch(fetchPayslip()); }, [dispatch]); const columns = [{ title: "Employee", render: (_, r) => r.employeeId?.name || r.employeeId }, { title: "Cycle", render: (_, r) => r.payrollCycleId?.name || "-" }, { title: "Gross", dataIndex: "grossSalary", render: currency }, { title: "Net", dataIndex: "netSalary", render: currency }, { title: "Download", render: (_, r) => <Button href={`/api/v1/payroll/payslips/${r._id}/download`}>Download</Button> }]; return <PageShell title="Payslips" subtitle="Filter and download employee payslips." actions={<Button onClick={() => dispatch(fetchPayslip())}>Refresh</Button>}><ResponsiveTable columns={columns} dataSource={payslip.items} loading={payslip.loading} /></PageShell>; }
export function PayrollReportsPage() { const dispatch = useDispatch(); const reports = useResource("payrollReport"); useEffect(() => { dispatch(fetchPayrollReport()); }, [dispatch]); return <PageShell title="Payroll Reports" subtitle="Summary, bank, PF, ESI, TDS and professional tax exports." actions={["bank-export", "pf", "esi", "tds", "professional-tax"].map((r) => <Button key={r} href={`/api/v1/payroll/reports/${r}?format=csv`}>{titleize(r)} Export</Button>)}><StatCards summary={reports.selected || reports.items?.[0]} loading={reports.loading} /></PageShell>; }
export function EmployeeLoanPage() { const dispatch = useDispatch(); const loans = useResource("employeeLoan"); const [open, setOpen] = useState(false); const [form] = Form.useForm(); useEffect(() => { dispatch(fetchEmployeeLoan()); }, [dispatch]); const columns = [{ title: "Employee", render: (_, r) => r.employeeId?.name || r.employeeId }, { title: "Principal", dataIndex: "principalAmount", render: currency }, { title: "Monthly", dataIndex: "monthlyDeduction", render: currency }, { title: "Remaining", dataIndex: "remainingAmount", render: currency }, { title: "Status", dataIndex: "status", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }]; return <PageShell title="Employee Loans" subtitle="Assign loans and track monthly deduction balances." actions={<Button type="primary" onClick={() => setOpen(true)}>Assign Loan</Button>}><ResponsiveTable columns={columns} dataSource={loans.items} loading={loans.loading} /><Modal open={open} title="Assign Loan" onCancel={() => setOpen(false)} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={async (values) => { await dispatch(createEmployeeLoan(values)); setOpen(false); dispatch(fetchEmployeeLoan()); }}><Form.Item name="employeeId" label="Employee User ID" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="principalAmount" label="Principal"><InputNumber min={0} style={{ width: "100%" }} /></Form.Item><Form.Item name="monthlyDeduction" label="Monthly Deduction"><InputNumber min={0} style={{ width: "100%" }} /></Form.Item><Form.Item name="startMonth" label="Start Month"><DatePicker picker="month" style={{ width: "100%" }} /></Form.Item></Form></Modal></PageShell>; }
export function ReimbursementAdminPage() { const dispatch = useDispatch(); const resource = useResource("reimbursement"); useEffect(() => { dispatch(fetchReimbursement()); }, [dispatch]); const columns = [{ title: "Employee", render: (_, r) => r.employeeId?.name || r.employeeId }, { title: "Title", dataIndex: "title" }, { title: "Amount", dataIndex: "amount", render: currency }, { title: "Status", dataIndex: "status", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }, { title: "Action", render: (_, r) => <Space><Button onClick={() => dispatch(updateReimbursement({ id: r._id, actionPath: "/status", data: { status: "approved" } }))}>Approve</Button><Button danger onClick={() => dispatch(updateReimbursement({ id: r._id, actionPath: "/status", data: { status: "rejected" } }))}>Reject</Button></Space> }]; return <PageShell title="Reimbursements" subtitle="Approve, reject and track employee reimbursement claims."><ResponsiveTable columns={columns} dataSource={resource.items} loading={resource.loading} /></PageShell>; }

export function MyPayrollDashboard() { const dispatch = useDispatch(); const payslip = useResource("payslip"); const loans = useResource("employeeLoan"); const reimbursements = useResource("reimbursement"); useEffect(() => { dispatch(fetchPayslip()); dispatch(fetchEmployeeLoan()); dispatch(fetchReimbursement()); }, [dispatch]); const latest = payslip.items?.[0] || {}; return <PageShell title="My Payroll" subtitle="Your salary, latest payslip, deductions, loan and reimbursement overview."><StatCards summary={{ currentPayroll: latest.netSalary, grossSalary: latest.grossSalary, totalDeductions: latest.totalDeductions, netSalary: latest.netSalary, employees: 1 }} loading={payslip.loading} /><Row gutter={[16,16]}><Col xs={24} md={12}><Card title="Loan Balance"><Statistic value={currency(safeArray(loans.items).reduce((t,l)=>t+Number(l.remainingAmount||0),0))} /></Card></Col><Col xs={24} md={12}><Card title="Reimbursements"><Statistic value={safeArray(reimbursements.items).filter((r)=>r.status==='pending').length} suffix="pending" /></Card></Col></Row></PageShell>; }
export function MyPayslipsPage() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { httpClient.get("/payroll/payslips/my").then((res) => setItems(res.data.data || [])).finally(() => setLoading(false)); }, []);
  const columns = [{ title: "Cycle", render: (_, r) => r.payrollCycleId?.name || "-" }, { title: "Gross", dataIndex: "grossSalary", render: currency }, { title: "Deductions", dataIndex: "totalDeductions", render: currency }, { title: "Net", dataIndex: "netSalary", render: currency }, { title: "Download", render: (_, r) => <Button href={`/api/v1/payroll/payslips/${r._id}/download`}>Download PDF</Button> }];
  return <PageShell title="My Payslips" subtitle="Month-wise payslips and secure downloads."><ResponsiveTable columns={columns} dataSource={items} loading={loading} /></PageShell>;
}
export function MyReimbursementsPage() { const dispatch = useDispatch(); const resource = useResource("reimbursement"); const [form] = Form.useForm(); useEffect(() => { dispatch(fetchReimbursement()); }, [dispatch]); const columns = [{ title: "Title", dataIndex: "title" }, { title: "Amount", dataIndex: "amount", render: currency }, { title: "Status", dataIndex: "status", render: (v) => <Tag color={statusColor(v)}>{titleize(v)}</Tag> }]; return <PageShell title="My Reimbursements" subtitle="Submit reimbursement claims and track approval status."><Card><Form form={form} layout="inline" onFinish={async (values) => { await dispatch(createReimbursement(values)); form.resetFields(); dispatch(fetchReimbursement()); }}><Form.Item name="title" rules={[{ required: true }]}><Input placeholder="Claim title" /></Form.Item><Form.Item name="amount" rules={[{ required: true }]}><InputNumber min={0} placeholder="Amount" /></Form.Item><Form.Item name="billUrl"><Input placeholder="Bill URL" /></Form.Item><Button htmlType="submit" type="primary">Submit</Button></Form></Card><ResponsiveTable columns={columns} dataSource={resource.items} loading={resource.loading} /></PageShell>; }
export function MyLoansPage() { return <EmployeeLoanPage />; }
export function MyTaxDeclarationPage() { return <PageShell title="My Tax Declaration" subtitle="PAN, regime selection, declarations and proof uploads."><Card><Form layout="vertical"><Row gutter={16}><Col xs={24} md={8}><Form.Item label="PAN"><Input /></Form.Item></Col><Col xs={24} md={8}><Form.Item label="Tax Regime"><Select options={["old", "new"].map((value)=>({ value, label: titleize(value) }))} /></Form.Item></Col><Col xs={24} md={8}><Form.Item label="Document URL"><Input /></Form.Item></Col></Row><Form.Item label="Declarations"><Input.TextArea rows={4} /></Form.Item><Button type="primary">Save Declaration</Button></Form></Card></PageShell>; }
export function PayrollOverviewPage() { return <PayrollDashboard />; }
export function PayrollTemplateSettingsPage() { return <PageShell title="Payroll Templates" subtitle="Default component templates and compliance settings for Super Admin rollout."><Tabs items={[{ key: "components", label: "Component Templates", children: <SalaryComponentsPage /> }, { key: "compliance", label: "Compliance Defaults", children: <PayrollSettingsPage /> }]} /></PageShell>; }
