import React from "react";
import { useSelector } from "react-redux";
import * as XLSX from "xlsx";
import dayjs from "dayjs";

const toRows = (items) =>
  items.map((r, idx) => ({
    "#": idx + 1,
    Type: r.type,
    School: r.school?.name || "-",
    Session: r.session?.name || "-",
    "Generated By": r.generatedBy?.name || "-",
    Status: r.status,
    "Created At": r.createdAt ? dayjs(r.createdAt).format("YYYY-MM-DD") : "-",
  }));

const downloadBlob = (content, filename, type) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const ExportButtons = () => {
  const { items = [] } = useSelector((state) => state.reports || {});

  const exportCsv = () => {
    if (!items.length) return;
    const rows = toRows(items);
    const headers = Object.keys(rows[0]);
    const csv = [headers, ...rows.map((r) => headers.map((h) => `"${r[h] ?? ""}"`))]
      .map((row) => row.join(","))
      .join("\n");
    downloadBlob(csv, `reports-${dayjs().format("YYYY-MM-DD")}.csv`, "text/csv");
  };

  const exportExcel = () => {
    if (!items.length) return;
    const ws = XLSX.utils.json_to_sheet(toRows(items));
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Reports");
    XLSX.writeFile(wb, `reports-${dayjs().format("YYYY-MM-DD")}.xlsx`);
  };

  const printReports = () => {
    if (!items.length) return;
    const rows = toRows(items);
    const headers = Object.keys(rows[0]);
    const html = `<html><head><title>Reports — ${dayjs().format("DD MMM YYYY")}</title>
      <style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse;margin-top:12px}
      th{background:#2563eb;color:white;padding:7px;font-size:12px;text-align:left}
      td{padding:6px 7px;border-bottom:1px solid #e2e8f0;font-size:12px}
      @media print{button{display:none}}</style></head><body>
      <h2>Reports — ${dayjs().format("DD MMMM YYYY")}</h2>
      <table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
      <tbody>${rows.map((r) => `<tr>${headers.map((h) => `<td>${r[h] ?? ""}</td>`).join("")}</tr>`).join("")}</tbody>
      </table></body></html>`;
    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    setTimeout(() => { win.print(); win.close(); }, 400);
  };

  const buttons = [
    { label: "PDF", onClick: printReports, title: "Opens the print dialog — choose \"Save as PDF\"" },
    { label: "Excel", onClick: exportExcel },
    { label: "CSV", onClick: exportCsv },
    { label: "Print", onClick: printReports },
  ];

  return (
    <div className="flex gap-2">
      {buttons.map((btn) => (
        <button
          key={btn.label}
          title={btn.title}
          disabled={!items.length}
          onClick={btn.onClick}
          className="bg-blue-500 hover:bg-blue-600 disabled:opacity-40 disabled:cursor-not-allowed text-white px-4 py-2 rounded"
        >
          {btn.label}
        </button>
      ))}
    </div>
  );
};

export default ExportButtons;
