import React, { useEffect, useMemo, useState } from "react";
import { Alert, Button, Card, Empty, Input, Modal, Select, Space, Spin, Table, Tag, Typography, message } from "antd";
import { useSelector } from "react-redux";
import httpClient from "../../api/httpClient";

const { Title, Text, Paragraph } = Typography;

const ACCESS_ROLES = ["Super Admin", "School Admin", "Teacher", "Principal", "Vice Principal"];

const getReportType = (report) => {
  if (report?.type) return String(report.type);
  if (report?.title?.toLowerCase()?.includes("attendance")) return "Attendance";
  if (report?.title?.toLowerCase()?.includes("fee")) return "Finance";
  if (report?.title?.toLowerCase()?.includes("exam")) return "Academic";
  return "General";
};

const formatDate = (value) => {
  if (!value) return "-";
  try {
    return new Date(value).toLocaleString();
  } catch {
    return "-";
  }
};

const DocumentsPage = () => {
  const user = useSelector((state) => state.auth?.user);
  const roleName = user?.role?.name || "";

  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState([]);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [selected, setSelected] = useState(null);

  const canViewDocuments = ACCESS_ROLES.includes(roleName);

  const loadReports = async () => {
    setLoading(true);
    try {
      const response = await httpClient.get("/report/getReport");
      setRows(response?.data?.data || []);
    } catch {
      try {
        const fallback = await httpClient.get("/report");
        setRows(fallback?.data?.data || []);
      } catch (error) {
        message.error(error?.response?.data?.message || "Failed to load documents");
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (canViewDocuments) {
      loadReports();
    } else {
      setLoading(false);
    }
  }, [canViewDocuments]);

  const typeOptions = useMemo(() => {
    const allTypes = Array.from(new Set(rows.map((row) => getReportType(row))));
    return [{ label: "All Types", value: "all" }, ...allTypes.map((value) => ({ label: value, value }))];
  }, [rows]);

  const filteredRows = useMemo(() => {
    const query = search.trim().toLowerCase();
    return rows.filter((row) => {
      const rowType = getReportType(row);
      const matchesType = typeFilter === "all" || rowType === typeFilter;
      const matchesSearch =
        !query ||
        [row?.title, row?.school?.name, row?.generatedBy?.name]
          .filter(Boolean)
          .join(" ")
          .toLowerCase()
          .includes(query);
      return matchesType && matchesSearch;
    });
  }, [rows, search, typeFilter]);

  const openDocument = async (record) => {
    if (!record?._id) return;

    try {
      const response = await httpClient.get(`/report/view/${record._id}`);
      setSelected(response?.data?.data || record);
    } catch {
      try {
        const fallback = await httpClient.get(`/report/${record._id}`);
        setSelected(fallback?.data?.data || record);
      } catch (error) {
        message.error(error?.response?.data?.message || "Failed to open document");
      }
    }
  };

  if (!canViewDocuments) {
    return (
      <Alert
        type="warning"
        showIcon
        message="Documents access is role-restricted"
        description="This module is currently available for Super Admin, School Admin and Teacher roles."
      />
    );
  }

  const columns = [
    {
      title: "Title",
      dataIndex: "title",
      key: "title",
      render: (value, record) => (
        <Space direction="vertical" size={0}>
          <Text strong>{value || "Untitled report"}</Text>
          <Text type="secondary" style={{ fontSize: 12 }}>#{record?._id?.slice(-6) || "------"}</Text>
        </Space>
      ),
    },
    {
      title: "Type",
      key: "type",
      render: (_value, record) => <Tag color="blue">{getReportType(record)}</Tag>,
    },
    {
      title: "School",
      key: "school",
      render: (_value, record) => record?.school?.name || "-",
    },
    {
      title: "Generated By",
      key: "generatedBy",
      render: (_value, record) => record?.generatedBy?.name || "-",
    },
    {
      title: "Created",
      dataIndex: "createdAt",
      key: "createdAt",
      render: (value) => formatDate(value),
    },
    {
      title: "Action",
      key: "action",
      render: (_value, record) => (
        <Button size="small" onClick={() => openDocument(record)}>
          View Detail
        </Button>
      ),
    },
  ];

  return (
    <Space direction="vertical" size={16} style={{ width: "100%" }}>
      <Card>
        <Space direction="vertical" size={2}>
          <Title level={4} style={{ margin: 0 }}>Documents</Title>
          <Text type="secondary">Report-backed document center with search, filters and detail preview.</Text>
        </Space>
      </Card>

      <Card>
        <Space wrap>
          <Input.Search
            allowClear
            placeholder="Search title, school, generated by"
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            style={{ width: 280 }}
          />
          <Select value={typeFilter} onChange={setTypeFilter} options={typeOptions} style={{ width: 180 }} />
        </Space>
      </Card>

      <Card title="Document List">
        {loading ? (
          <div style={{ textAlign: "center", padding: 20 }}><Spin /></div>
        ) : filteredRows.length === 0 ? (
          <Empty description="No documents found" />
        ) : (
          <Table
            rowKey={(record) => record._id}
            columns={columns}
            dataSource={filteredRows}
            pagination={{ pageSize: 10 }}
          />
        )}
      </Card>

      <Modal
        title={selected?.title || "Document Detail"}
        open={Boolean(selected)}
        onCancel={() => setSelected(null)}
        footer={null}
        width={760}
      >
        {selected && (
          <Space direction="vertical" size={10} style={{ width: "100%" }}>
            <Space>
              <Tag>{getReportType(selected)}</Tag>
              <Text type="secondary">Created: {formatDate(selected.createdAt)}</Text>
            </Space>
            <Text strong>Generated By:</Text>
            <Text>{selected?.generatedBy?.name || "-"}</Text>
            <Text strong>School:</Text>
            <Text>{selected?.school?.name || "-"}</Text>
            <Text strong>Data:</Text>
            <Paragraph style={{ whiteSpace: "pre-wrap", maxHeight: 300, overflowY: "auto" }}>
              {typeof selected?.data === "string" ? selected.data : JSON.stringify(selected?.data || {}, null, 2)}
            </Paragraph>
          </Space>
        )}
      </Modal>
    </Space>
  );
};

export default DocumentsPage;