import React, { useState } from 'react';
import { ScrollView, View } from 'react-native';
import { Button, Chip, IconButton, Text } from 'react-native-paper';
import { QueryState } from '../../components/ui/QueryState';
import { AccentListCard } from '../../components/ui/AccentListCard';
import { IconWell } from '../../components/ui/IconWell';
import { StatCard, StatGrid } from '../../components/ui/StatCard';
import { StatusPill } from '../../components/ui/StatusPill';
import { CreateReportSheet } from './CreateReportSheet';
import { formatDate } from '../../utils/format';
import { confirmDelete } from '../../utils/confirm';
import { useAppTheme } from '../../theme/ThemeProvider';
import { useDeleteReportMutation, useGetDashboardSummaryQuery, useGetReportsQuery } from '../../store/api/apiSlice';

const TYPE_COLOR = { fees: '#22C55E', students: '#2563EB', attendance: '#F59E0B', performance: '#7C3AED', custom: '#94A3B8' };
const TYPES = [null, 'fees', 'students', 'attendance', 'performance', 'custom'];

/** Report builder — confirmed to be a generic "save a titled data blob" CRUD, not a real
 * computation engine (nothing runs server-side; the web app's own chart is hardcoded fake data
 * and its export buttons have no handlers at all) — those pieces are deliberately not
 * reproduced here since they don't do anything on the real app either. Mirrors
 * frontend/src/pages/Super_Admin/Reports_&Analytics/Reports.jsx's real (working) parts: summary
 * cards + saved-reports list + create + delete. */
export function SuperAdminReportsView() {
  const { colors, typography, spacing } = useAppTheme();
  const [type, setType] = useState(null);
  const [creating, setCreating] = useState(false);

  const summaryQuery = useGetDashboardSummaryQuery();
  const summary = summaryQuery.data ?? {};

  const { data, isLoading, isFetching, isError, error, refetch } = useGetReportsQuery({ type: type || undefined });
  const reports = data ?? [];
  const [deleteReport, deleteState] = useDeleteReportMutation();

  return (
    <View>
      <View style={{ marginBottom: spacing.lg }}>
        <StatGrid>
          <StatCard label="Schools" metric={{ label: 'Schools', icon: 'domain', color: colors.primary, value: summary.schools ?? 0 }} />
          <StatCard label="Admins" metric={{ label: 'Admins', icon: 'shield-account-outline', color: '#7C3AED', value: summary.admins ?? 0 }} />
          <StatCard label="Users" metric={{ label: 'Users', icon: 'account-group-outline', color: '#22C55E', value: summary.users ?? 0 }} />
          <StatCard label="Fees Collected" metric={{ label: 'Fees Collected', icon: 'cash-multiple', color: '#F59E0B', value: summary.feesCollected ?? 0, format: 'currency' }} />
        </StatGrid>
      </View>

      <View style={{ flexDirection: 'row', justifyContent: 'flex-end', marginBottom: spacing.md }}>
        <Button mode="contained" icon="plus" onPress={() => setCreating(true)}>
          New Report
        </Button>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexGrow: 0 }} contentContainerStyle={{ gap: spacing.sm, paddingBottom: spacing.md, alignItems: 'center' }}>
        {TYPES.map((t) => (
          <Chip key={t || 'all'} selected={type === t} onPress={() => setType(t)}>
            {t ?? 'All'}
          </Chip>
        ))}
      </ScrollView>

      <QueryState
        isLoading={isLoading || isFetching}
        isError={isError}
        error={error}
        onRetry={refetch}
        isEmpty={reports.length === 0}
        emptyIcon="chart-box-outline"
        emptyLabel="No reports saved yet"
      >
        {reports.map((r) => (
          <AccentListCard
            key={r._id}
            accent={TYPE_COLOR[r.type] || colors.primary}
            avatar={<IconWell icon="chart-box-outline" color={TYPE_COLOR[r.type] || colors.primary} size={38} />}
            title={r.title}
            subtitle={r.school?.name ?? ''}
            badge={<StatusPill label={r.type} color={TYPE_COLOR[r.type] || colors.textMuted} />}
            meta={[
              { label: 'Generated By', value: r.generatedBy?.name ?? '—' },
              { label: 'Created', value: formatDate(r.createdAt) },
              { label: 'Status', value: r.status },
              { label: 'Data', value: typeof r.data === 'string' ? r.data : JSON.stringify(r.data) },
            ]}
            expandable
            actions={<IconButton icon="trash-can-outline" iconColor={colors.danger} size={18} disabled={deleteState.isLoading} onPress={() => confirmDelete(() => deleteReport(r._id), 'this report')} />}
          />
        ))}
      </QueryState>

      <CreateReportSheet visible={creating} onDismiss={() => setCreating(false)} onCreated={() => setCreating(false)} />
    </View>
  );
}
